<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

//        echo "<pre>" ;
//        print_r($bob);
//        echo "</pre>";
//                //print_r($this->bob);
////exit;
$client = new Github/Client();
echo 'hi'; exit;
$repositories = $client->api('user')->repositories('ornicar');

    $username = 'refais23';
    $repo = 'jp-test';
    echo 'hi'; exit;
    $users = $client->api('issue')->all('KnpLabs', 'php-github-api', array('state' => 'open'));
    echo '<pre>';
    echo print_r($users) ;
    echo '</pre>'; 
    exit;
?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        ?>
    </body>
</html>
